apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: reaqta
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: erdiugurlu/reaqta-helloworld:0.10
        ports:
        - containerPort: 8080

